cc_binary(
    name = 'epoll-server',
    srcs = [
        'common.cpp',
        'epoll-server.cpp',
        'package.cpp'
    ],
    optimize = [
        '-std=c++11',
    ]
)

cc_binary(
    name = 'client',
    srcs = [
        'client.cpp',
        'common.cpp'
    ],
    optimize = [
        '-std=c++11',
    ]
)
