cc_binary(
    name = 'epoll-server',
    srcs = [
        'common.cpp',
        'epoll-server.cpp',
        'package.cpp'
    ]
)

cc_binary(
    name = 'telnet-client',
    srcs = [
        'telnet-client.cpp',
        'common.cpp'
    ]
)
